export const cities = [
  { id: '1', text: 'Phnom Penh', value: 'PP' },
  { id: '2', text: 'Siem Reap', value: 'SR' },
  { id: '3', text: 'Battambang', value: 'BTB' },
  { id: '4', text: 'Sihanoukville', value: 'SHV' },
  { id: '5', text: 'Kampong Cham', value: 'KPC' },
  { id: '6', text: 'Kampong Thom', value: 'KPT' },
  { id: '7', text: 'Poipet', value: 'PPT' },
  { id: '8', text: 'Ta Khmau', value: 'TK' },
  { id: '9', text: 'Kampot', value: 'KP' },
  { id: '10', text: 'Sisophon', value: 'SIS' },
  { id: '11', text: 'Takhmau', value: 'TM' },
  { id: '12', text: 'Pursat', value: 'PS' },
  { id: '13', text: 'Krong Suong', value: 'KS' },
  { id: '14', text: 'Krong Preah Vihear', value: 'KPV' },
  { id: '15', text: 'Kampong Speu', value: 'KPS' },
  { id: '16', text: 'Kratie', value: 'KRT' },
  { id: '17', text: 'Stung Treng', value: 'ST' },
  { id: '18', text: 'Svay Rieng', value: 'SVR' },
  { id: '19', text: 'Prey Veng', value: 'PV' },
  { id: '20', text: 'Banlung', value: 'BL' },
  { id: '21', text: 'Senmonorom', value: 'SM' },
  { id: '22', text: 'Pailin', value: 'PL' },
]
